"""In-memory demo store providing complete SIH dataset when PostgreSQL is offline."""
import uuid
from datetime import datetime, timedelta
from typing import Dict, Any, List

MINE_A_ID = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
SUB_1_ID = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"

DEMO_MINES = [
    {
        "id": MINE_A_ID,
        "name": "Mine A — Ramgarh Colliery",
        "code": "MINE-A",
        "subsidiary_id": SUB_1_ID,
        "location_name": "Ramgarh, Jharkhand",
        "state": "Jharkhand",
        "district": "Ramgarh",
        "latitude": 23.6250,
        "longitude": 85.5140,
        "mine_type": "underground",
        "capacity_mtpa": 2.5,
        "is_active": True,
    },
    {
        "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02",
        "name": "Mine B — Dhanbad Seam 4",
        "code": "MINE-B",
        "subsidiary_id": SUB_1_ID,
        "location_name": "Dhanbad, Jharkhand",
        "state": "Jharkhand",
        "district": "Dhanbad",
        "latitude": 23.7957,
        "longitude": 86.4304,
        "mine_type": "underground",
        "capacity_mtpa": 3.2,
        "is_active": True,
    },
    {
        "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03",
        "name": "Mine C — Singrauli Open Pit",
        "code": "MINE-C",
        "subsidiary_id": SUB_1_ID,
        "location_name": "Singrauli, MP",
        "state": "Madhya Pradesh",
        "district": "Singrauli",
        "latitude": 24.1997,
        "longitude": 82.6644,
        "mine_type": "opencast",
        "capacity_mtpa": 4.8,
        "is_active": True,
    },
    {
        "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04",
        "name": "Mine D — Korba South Colliery",
        "code": "MINE-D",
        "subsidiary_id": SUB_1_ID,
        "location_name": "Korba, Chhattisgarh",
        "state": "Chhattisgarh",
        "district": "Korba",
        "latitude": 22.3595,
        "longitude": 82.7501,
        "mine_type": "opencast",
        "capacity_mtpa": 3.0,
        "is_active": True,
    },
]

DEMO_VIOLATIONS = [
    {
        "id": "vvvvvvvv-0001-0000-0000-000000000001",
        "reference_number": "VIO-20261001-001",
        "mine_id": MINE_A_ID,
        "category": "Ventilation",
        "severity": "critical",
        "description": "Auxiliary fan tripped in underground Seam 3 Block 4, airflow low below statutory threshold",
        "compliance_status": "non_compliant",
        "is_recurring": True,
        "latitude": 23.6260,
        "longitude": 85.5150,
        "created_at": (datetime.utcnow() - timedelta(hours=6)).isoformat(),
    },
    {
        "id": "vvvvvvvv-0002-0000-0000-000000000002",
        "reference_number": "VIO-20261001-002",
        "mine_id": MINE_A_ID,
        "category": "Fire Safety",
        "severity": "critical",
        "description": "Expired fire extinguishers and coal dust accumulation on electrical junction panel",
        "compliance_status": "non_compliant",
        "is_recurring": False,
        "latitude": 23.6245,
        "longitude": 85.5135,
        "created_at": (datetime.utcnow() - timedelta(hours=14)).isoformat(),
    },
    {
        "id": "vvvvvvvv-0003-0000-0000-000000000003",
        "reference_number": "VIO-20260930-003",
        "mine_id": MINE_A_ID,
        "category": "PPE",
        "severity": "high",
        "description": "Four workers observed without mandatory reflective safety jackets and chin-strap helmets",
        "compliance_status": "non_compliant",
        "is_recurring": True,
        "latitude": 23.6255,
        "longitude": 85.5142,
        "created_at": (datetime.utcnow() - timedelta(days=1, hours=3)).isoformat(),
    },
    {
        "id": "vvvvvvvv-0004-0000-0000-000000000004",
        "reference_number": "VIO-20260929-004",
        "mine_id": MINE_A_ID,
        "category": "Electrical Safety",
        "severity": "high",
        "description": "Damaged cable insulation and water seepage near Substation 2",
        "compliance_status": "warning",
        "is_recurring": False,
        "latitude": 23.6238,
        "longitude": 85.5128,
        "created_at": (datetime.utcnow() - timedelta(days=2)).isoformat(),
    },
    {
        "id": "vvvvvvvv-0005-0000-0000-000000000005",
        "reference_number": "VIO-20260928-005",
        "mine_id": MINE_A_ID,
        "category": "Environmental",
        "severity": "medium",
        "description": "Dust suppression sprinklers water pressure inadequate at coal handling haul road",
        "compliance_status": "warning",
        "is_recurring": False,
        "latitude": 23.6272,
        "longitude": 85.5165,
        "created_at": (datetime.utcnow() - timedelta(days=3)).isoformat(),
    },
    {
        "id": "vvvvvvvv-0006-0000-0000-000000000006",
        "reference_number": "VIO-20260927-006",
        "mine_id": MINE_A_ID,
        "category": "PPE",
        "severity": "medium",
        "description": "Ear protection missing during drilling operations at development heading",
        "compliance_status": "compliant",
        "is_recurring": True,
        "latitude": 23.6248,
        "longitude": 85.5139,
        "created_at": (datetime.utcnow() - timedelta(days=4)).isoformat(),
    },
]

DEMO_TASKS = [
    {
        "id": "tttttttt-0001-0000-0000-000000000001",
        "title": "Repair & Restore Seam 3 Auxiliary Ventilation Fan",
        "description": "Emergency ventilation repair to restore 450 m3/min airflow per CMR 2017 Regulation 153",
        "mine_id": MINE_A_ID,
        "priority": "critical",
        "status": "assigned",
        "assignee": "A. K. Sharma (Ventilation In-Charge)",
        "due_date": (datetime.utcnow() + timedelta(hours=4)).isoformat(),
        "created_at": (datetime.utcnow() - timedelta(hours=6)).isoformat(),
        "is_overdue": False,
        "violation_id": "vvvvvvvv-0001-0000-0000-000000000001",
    },
    {
        "id": "tttttttt-0002-0000-0000-000000000002",
        "title": "Replace Expired Fire Extinguishers & Clean Electrical Junctions",
        "description": "Deploy fresh dry chemical powder extinguishers and remove combustible coal dust",
        "mine_id": MINE_A_ID,
        "priority": "critical",
        "status": "in_progress",
        "assignee": "P. N. Roy (Safety Officer)",
        "due_date": (datetime.utcnow() + timedelta(hours=10)).isoformat(),
        "created_at": (datetime.utcnow() - timedelta(hours=14)).isoformat(),
        "is_overdue": False,
        "violation_id": "vvvvvvvv-0002-0000-0000-000000000002",
    },
    {
        "id": "tttttttt-0003-0000-0000-000000000003",
        "title": "Conduct Mandatory PPE Safety Refresher & Issue New Gear",
        "description": "Section-wide PPE compliance audit and reissue of reflective harness kits",
        "mine_id": MINE_A_ID,
        "priority": "high",
        "status": "escalated",
        "assignee": "R. K. Verma (Mining Sirdar)",
        "due_date": (datetime.utcnow() - timedelta(hours=8)).isoformat(),
        "created_at": (datetime.utcnow() - timedelta(days=1, hours=3)).isoformat(),
        "is_overdue": True,
        "violation_id": "vvvvvvvv-0003-0000-0000-000000000003",
    },
    {
        "id": "tttttttt-0004-0000-0000-000000000004",
        "title": "Rewire & Waterproof Substation 2 Feeders",
        "description": "Seal water seepage and renew armored cable sleeves",
        "mine_id": MINE_A_ID,
        "priority": "high",
        "status": "resolved",
        "assignee": "Sunil Murmu (Electrical Supervisor)",
        "due_date": (datetime.utcnow() + timedelta(days=1)).isoformat(),
        "created_at": (datetime.utcnow() - timedelta(days=2)).isoformat(),
        "is_overdue": False,
        "violation_id": "vvvvvvvv-0004-0000-0000-000000000004",
    },
]

DEMO_INSPECTIONS = [
    {
        "id": "iiiiiiii-0001-0000-0000-000000000001",
        "title": "Monthly Statutory Safety Audit — Underground Section",
        "reference_number": "INSP-202610-001",
        "mine_id": MINE_A_ID,
        "mine_name": "Mine A — Ramgarh Colliery",
        "inspector_name": "Amit Patel (Field Officer)",
        "status": "in_progress",
        "observations_count": 5,
        "violations_count": 2,
        "created_at": (datetime.utcnow() - timedelta(hours=8)).isoformat(),
    },
    {
        "id": "iiiiiiii-0002-0000-0000-000000000002",
        "title": "Conveyor Belt & Haulage Safety Inspection",
        "reference_number": "INSP-202609-042",
        "mine_id": MINE_A_ID,
        "mine_name": "Mine A — Ramgarh Colliery",
        "inspector_name": "Priya Sharma (Compliance Officer)",
        "status": "completed",
        "observations_count": 8,
        "violations_count": 3,
        "created_at": (datetime.utcnow() - timedelta(days=3)).isoformat(),
    },
    {
        "id": "iiiiiiii-0003-0000-0000-000000000003",
        "title": "Quarterly Environmental Clearance & Water Quality Check",
        "reference_number": "INSP-202609-019",
        "mine_id": MINE_A_ID,
        "mine_name": "Mine A — Ramgarh Colliery",
        "inspector_name": "Priya Sharma (Compliance Officer)",
        "status": "completed",
        "observations_count": 4,
        "violations_count": 1,
        "created_at": (datetime.utcnow() - timedelta(days=7)).isoformat(),
    },
]

DEMO_NOTIFICATIONS = [
    {
        "id": "nnnnnnnn-0001-0000-0000-000000000001",
        "title": "Critical Hazard Alert: Ventilation Dropped",
        "message": "Auxiliary fan tripped in Seam 3 Block 4. Airflow below statutory 450 m3/min.",
        "severity": "critical",
        "is_read": False,
        "action_url": "/tasks",
        "created_at": (datetime.utcnow() - timedelta(minutes=25)).isoformat(),
    },
    {
        "id": "nnnnnnnn-0002-0000-0000-000000000002",
        "title": "Task Overdue: PPE Safety Refresher",
        "message": "Task #TASK-003 assigned to R. K. Verma is now overdue by 8 hours.",
        "severity": "high",
        "is_read": False,
        "action_url": "/tasks",
        "created_at": (datetime.utcnow() - timedelta(hours=2)).isoformat(),
    },
    {
        "id": "nnnnnnnn-0003-0000-0000-000000000003",
        "title": "Inspection Synchronized",
        "message": "Offline inspection INSP-202610-001 synced with server database.",
        "severity": "low",
        "is_read": True,
        "action_url": "/inspections",
        "created_at": (datetime.utcnow() - timedelta(hours=5)).isoformat(),
    },
]

DEMO_AUDIT_LOGS = [
    {
        "id": "aaaaaaaa-0001-0000-0000-000000000001",
        "timestamp": (datetime.utcnow() - timedelta(hours=6)).isoformat(),
        "action": "VIOLATION_AND_TASK_CREATED",
        "entity_type": "violation",
        "entity_id": "vvvvvvvv-0001-0000-0000-000000000001",
        "old_value": None,
        "new_value": {"severity": "critical", "category": "Ventilation", "deadline": "24h"},
        "record_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "previous_hash": None,
    },
    {
        "id": "aaaaaaaa-0002-0000-0000-000000000002",
        "timestamp": (datetime.utcnow() - timedelta(hours=5, minutes=45)).isoformat(),
        "action": "TASK_ASSIGNED",
        "entity_type": "task",
        "entity_id": "tttttttt-0001-0000-0000-000000000001",
        "old_value": {"status": "open"},
        "new_value": {"status": "assigned", "assignee": "A. K. Sharma"},
        "record_hash": "c782b683395b2cebc4c407c6f09b5522b2b3a8e97f0fb5255476de808801d011",
        "previous_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    },
    {
        "id": "aaaaaaaa-0003-0000-0000-000000000003",
        "timestamp": (datetime.utcnow() - timedelta(hours=1)).isoformat(),
        "action": "TASK_ESCALATED",
        "entity_type": "task",
        "entity_id": "tttttttt-0003-0000-0000-000000000003",
        "old_value": {"status": "assigned"},
        "new_value": {"status": "escalated", "reason": "Statutory deadline exceeded"},
        "record_hash": "9f83c07641d6b0e8b2b627ca9804e0a44d0df276536b53a3e6f9d2df80753023",
        "previous_hash": "c782b683395b2cebc4c407c6f09b5522b2b3a8e97f0fb5255476de808801d011",
    },
    {
        "id": "aaaaaaaa-0004-0000-0000-000000000004",
        "timestamp": (datetime.utcnow() - timedelta(minutes=15)).isoformat(),
        "action": "TASK_VERIFIED_AND_CLOSED",
        "entity_type": "task",
        "entity_id": "tttttttt-0004-0000-0000-000000000004",
        "old_value": {"status": "resolved"},
        "new_value": {"status": "closed", "verified": True, "approver": "P. N. Roy"},
        "record_hash": "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b",
        "previous_hash": "9f83c07641d6b0e8b2b627ca9804e0a44d0df276536b53a3e6f9d2df80753023",
    },
]


def get_demo_dashboard_data(mine_id: str | None = None) -> Dict[str, Any]:
    return {
        "mine_id": mine_id or MINE_A_ID,
        "generated_at": datetime.utcnow().isoformat(),
        "period_days": 30,
        "kpis": {
            "compliance_pct": 87.4,
            "critical_risks": 3,
            "high_risks": 8,
            "medium_risks": 14,
            "low_risks": 12,
            "overdue_actions": 4,
            "recurring_violations": 3,
            "pending_actions": 7,
            "total_violations": 37,
            "total_inspections": 18,
        },
        "violations_by_category": [
            {"category": "PPE", "count": 12},
            {"category": "Ventilation", "count": 8},
            {"category": "Fire Safety", "count": 6},
            {"category": "Electrical Safety", "count": 5},
            {"category": "Environmental", "count": 4},
            {"category": "Haulage", "count": 2},
        ],
        "violation_trend": [
            {"date": (datetime.utcnow() - timedelta(days=6)).strftime("%b %d"), "critical": 1, "high": 2, "medium": 3, "low": 2},
            {"date": (datetime.utcnow() - timedelta(days=5)).strftime("%b %d"), "critical": 0, "high": 1, "medium": 2, "low": 1},
            {"date": (datetime.utcnow() - timedelta(days=4)).strftime("%b %d"), "critical": 1, "high": 0, "medium": 4, "low": 3},
            {"date": (datetime.utcnow() - timedelta(days=3)).strftime("%b %d"), "critical": 0, "high": 2, "medium": 1, "low": 2},
            {"date": (datetime.utcnow() - timedelta(days=2)).strftime("%b %d"), "critical": 2, "high": 1, "medium": 2, "low": 1},
            {"date": (datetime.utcnow() - timedelta(days=1)).strftime("%b %d"), "critical": 1, "high": 3, "medium": 3, "low": 2},
            {"date": datetime.utcnow().strftime("%b %d"), "critical": 1, "high": 1, "medium": 1, "low": 1},
        ],
        "task_status_breakdown": {
            "open": 5,
            "assigned": 8,
            "in_progress": 6,
            "escalated": 4,
            "resolved": 9,
            "verified": 12,
            "closed": 15,
        },
        "recent_inspections": DEMO_INSPECTIONS,
        "critical_alerts": [
            {
                "id": "tttttttt-0001-0000-0000-000000000001",
                "title": "Repair & Restore Seam 3 Auxiliary Ventilation Fan",
                "status": "assigned",
                "priority": "critical",
                "due_date": (datetime.utcnow() + timedelta(hours=4)).isoformat(),
            },
            {
                "id": "tttttttt-0002-0000-0000-000000000002",
                "title": "Replace Expired Fire Extinguishers & Clean Electrical Junctions",
                "status": "in_progress",
                "priority": "critical",
                "due_date": (datetime.utcnow() + timedelta(hours=10)).isoformat(),
            },
        ],
    }
