"""Report generation service."""
import os
import uuid
from datetime import datetime
from typing import Any
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from app.config import settings
from app.models import Violation, Task, Inspection, Mine, SeverityLevel, TaskStatus


async def generate_report_sync(
    job_id: str,
    data: Any,
    db: AsyncSession,
) -> str:
    """Generate a simple PDF report. Returns file path."""
    # Collect data
    report_data = await _collect_report_data(data, db)

    # Generate simple HTML report (PDF in production via weasyprint)
    html_content = _render_html_report(report_data, data.report_type)

    # Save as HTML for now (replace with PDF in production)
    report_dir = os.path.join(settings.UPLOAD_DIR, "reports")
    os.makedirs(report_dir, exist_ok=True)
    filename = f"report_{job_id}_{data.report_type}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.html"
    file_path = os.path.join(report_dir, filename)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return f"/uploads/reports/{filename}"


async def _collect_report_data(data: Any, db: AsyncSession) -> dict:
    """Collect metrics for the report."""
    result = {}

    if data.mine_id:
        mine_uuid = uuid.UUID(data.mine_id)

        # Get mine info
        mine_result = await db.execute(select(Mine).where(Mine.id == mine_uuid))
        mine = mine_result.scalar_one_or_none()
        result["mine_name"] = mine.name if mine else "Unknown"
        result["mine_code"] = mine.code if mine else "N/A"

        # Violation counts
        sev_counts = await db.execute(
            select(Violation.severity, func.count(Violation.id))
            .where(Violation.mine_id == mine_uuid)
            .group_by(Violation.severity)
        )
        result["violations_by_severity"] = {row[0].value: row[1] for row in sev_counts.all()}

        # Task status
        task_counts = await db.execute(
            select(Task.status, func.count(Task.id))
            .where(Task.mine_id == mine_uuid)
            .group_by(Task.status)
        )
        result["tasks_by_status"] = {row[0].value: row[1] for row in task_counts.all()}

    result["generated_at"] = datetime.utcnow().isoformat()
    result["report_type"] = data.report_type
    return result


def _render_html_report(data: dict, report_type: str) -> str:
    """Render a professional HTML report."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Coal Mine Compliance Report — {report_type.upper()}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a2332; }}
  h1 {{ color: #0f2d5b; border-bottom: 3px solid #0f2d5b; padding-bottom: 10px; }}
  h2 {{ color: #1e4a8a; }}
  .kpi {{ display: inline-block; margin: 10px; padding: 15px 20px; background: #f0f4fb; border-left: 4px solid #0f2d5b; min-width: 150px; }}
  .kpi-value {{ font-size: 28px; font-weight: bold; color: #0f2d5b; }}
  .kpi-label {{ font-size: 12px; color: #666; text-transform: uppercase; }}
  .critical {{ border-left-color: #dc2626; }}
  .high {{ border-left-color: #ea580c; }}
  .medium {{ border-left-color: #ca8a04; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th {{ background: #0f2d5b; color: white; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }}
  .footer {{ margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #e2e8f0; padding-top: 10px; }}
  .watermark {{ background: #fef3c7; border: 1px solid #f59e0b; padding: 8px; margin-bottom: 20px; font-size: 12px; }}
</style>
</head>
<body>
<h1>🏭 Coal Mine Compliance Report</h1>
<div class="watermark">⚠️ SYNTHETIC DEMO DATA — Not based on real Coal India or government data</div>

<h2>Mine: {data.get('mine_name', 'All Mines')} ({data.get('mine_code', '')})</h2>
<p><strong>Report Type:</strong> {report_type.upper()} | <strong>Generated:</strong> {data.get('generated_at', '')}</p>

<h2>Violation Summary</h2>
<div>
{''.join([
    f'<div class="kpi {sev}"><div class="kpi-value">{count}</div><div class="kpi-label">{sev.upper()}</div></div>'
    for sev, count in data.get('violations_by_severity', {}).items()
])}
</div>

<h2>Task Status</h2>
<table>
<tr><th>Status</th><th>Count</th></tr>
{''.join([
    f'<tr><td>{status}</td><td>{count}</td></tr>'
    for status, count in data.get('tasks_by_status', {}).items()
])}
</table>

<div class="footer">
Report generated by AI Coal Mine Governance System v1.0 | 
Synthetic demo data for SIH prototype demonstration | 
All metrics derived from database records
</div>
</body>
</html>"""
